apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.30.0
    chart: vault
    helm:
      releaseName: vault-rele
      parameters:
        - name: ui.enabled
          value: 'true'
        - name: ui.serviceType
          value: LoadBalancer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true