apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: monitoring
spec:
  project: monitoring
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: latest
    helm:
      releaseName: grafana
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring