apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 9.3.2
    chart: grafana
    helm:
    valueFiles:
      - ./values.yaml 
  sources: []
  project: monitoring
  syncPolicy:
    automated: null