apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 21.1.23
    helm:
      releaseName: nginx
      valueFiles:
        - https://raw.githubusercontent.com/sofiengwin/kube-infra/refs/heads/master/apps/nginx/values.yml
