apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fiq
  namespace: production
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/fiq.git
    targetRevision: HEAD
    path: .chart
    helm:
      parameters:
        - name: env.DATABASE_URL
          value: "postgresql://user:password@postgres-host:5432/fiq_production"
        - name: env.REDIS_URL_SIDEKIQ
          value: "redis://redis-host:6379/0"
        - name: env.API_FOOTBALL_KEY
          value: "your-api-football-key"
        - name: image.tag
          value: "latest"
        - name: replicaCount
          value: "1"
        - name: env.RAILS_ENV
          value: "production"
        - name: env.RACK_ENV
          value: "production"
        - name: env.RAILS_LOG_TO_STDOUT
          value: "true"
        - name: env.RAILS_SERVE_STATIC_FILES
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: production