apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: root-ingress
  namespace: argocd
spec:
  rules:
    - host: "argocd.godwinogbara.com"
      http:
        paths:
          - backend:
              service:
                name: argocd-server
                port:
                  number: 8080
            pathType: Prefix
            path: /
    - host: "guestbook.godwinogbara.com"
      http:
        paths:
        - backend:
            service:
              name: guestbook-helm-guestbook
              port:
                number: 80
          path: /
          pathType: Prefix