apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.37.0
    helm:
      releaseName: loki
      values: |
        deploymentMode: SingleBinary

        singleBinary:
          replicas: 1

        write:
          replicas: 0
        read:
          replicas: 0
        backend:
          replicas: 0

        chunksCache:
          enabled: false
        resultsCache:
          enabled: false

        test:
          enabled: false

        ingress:
          enabled: true
          hosts:
            - loki.godwinogbara.com
          ingressClassName: traefik

        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          useTestSchema: true
